spring.application.name=TH1

# PostgreSQL - Supabase (Session pooler)
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.lpmzpluebbqropciuwju
spring.datasource.password=.s.yaxG3L%75Pa3

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=day-la-chuoi-bi-mat-ra-dai-nhat-32-ky-tu-bat-buoc
jwt.expiration=86400000
